Repository Reine0017/team-36-codeu, pull requests merged in 2019-07, with the labels that each got.

#21 Images #2 - Allow users to directly upload image files
  .factorypath
  src/main/java/com/google/codeu/servlets/BlobstoreUploadUrlServlet.java
  src/main/java/com/google/codeu/servlets/LoginServlet.java
  src/main/java/com/google/codeu/servlets/MessageServlet.java
  src/main/webapp/js/user-page-loader.js
  src/main/webapp/user-page.html
Labels: enhancement, ready to merge

#29 Reine branch ui
  src/main/webapp/aboutus.html
  src/main/webapp/community.html
  src/main/webapp/css/aboutus_style.css
  src/main/webapp/css/indexPage.css
  src/main/webapp/css/main.css
  src/main/webapp/css/moreInfo.css
  src/main/webapp/css/navbar.css
  src/main/webapp/css/swiper.min.css
  src/main/webapp/feed.html
  src/main/webapp/images/Ali_1.jpg
  src/main/webapp/images/Meg_1.jpg
  src/main/webapp/images/Reine_1.jpg
  src/main/webapp/images/cinema_2.jpg
  src/main/webapp/images/cinema_5.jpg
  src/main/webapp/images/cinema_8.jpg
  src/main/webapp/images/m1.png
  src/main/webapp/images/m2.png
  src/main/webapp/images/m3.png
  src/main/webapp/images/m4.png
  src/main/webapp/images/m5.png
  src/main/webapp/images/movieTicket.png
  src/main/webapp/images/movie_reel.jpg
  src/main/webapp/images/popcornIcon.png
  src/main/webapp/images/smoke.mp4
  src/main/webapp/index.html
  src/main/webapp/js/main.js
  src/main/webapp/js/moreInfo-loader.js
  src/main/webapp/js/swiper.min.js
  src/main/webapp/stats.html
  src/main/webapp/user-page.html
Labels: WIP

#31 Reine UI
  src/main/webapp/aboutus.html
  src/main/webapp/css/aboutus_style.css
  src/main/webapp/css/indexPage.css
  src/main/webapp/css/maps-page.css
  src/main/webapp/css/moreInfo.css
  src/main/webapp/css/selectionMenu.css
  src/main/webapp/css/user-page.css
  src/main/webapp/feed.html
  src/main/webapp/images/closeButton_1.png
  src/main/webapp/images/seat.png
  src/main/webapp/index.html
  src/main/webapp/js/maps-page-loader.js
  src/main/webapp/maps.html
  src/main/webapp/user-page.html
Labels: ready to merge

#33 Replace parentkey filter with datastore ancestor path
  src/main/java/com/google/codeu/data/Datastore.java
  src/main/java/com/google/codeu/data/Marker.java
  src/main/java/com/google/codeu/data/Message.java
  src/main/java/com/google/codeu/servlets/MarkerMessagesServlet.java
  src/main/java/com/google/codeu/servlets/MessageByKeyServlet.java
  src/main/java/com/google/codeu/servlets/MessageFeedServlet.java
Labels: ready to merge

#43 changed to placeholder for submit reviews
  src/main/webapp/maps.html
Labels: ready to merge

#44 Change redirection to display only messages for specified cinema
  src/main/java/com/google/codeu/servlets/MarkerMessagesServlet.java
  src/main/java/com/google/codeu/servlets/MessageFeedServlet.java
  src/main/webapp/js/maps-page-loader.js
  src/main/webapp/js/messages-loader.js
  src/main/webapp/maps.html
Labels: ready to merge

#47 Add selection of cinema to view
  src/main/webapp/feed.html
  src/main/webapp/js/messages-loader.js
Labels: ready to merge

#50 Add Login and Restore YourPage
  src/main/webapp/aboutus.html
  src/main/webapp/feed.html
  src/main/webapp/js/maps-page-loader.js
  src/main/webapp/js/user-page-loader.js
  src/main/webapp/maps.html
  src/main/webapp/user-page.html
Labels: ready to merge

#41 auto-refresh feed after 8s
  src/main/webapp/css/user-page.css
  src/main/webapp/feed.html
  src/main/webapp/js/messages-loader.js
Labels: ready to merge

#48 Select respective option after redirection
  src/main/webapp/js/messages-loader.js
Labels: ready to merge

#49 Feed style
  src/main/webapp/css/feed.css
  src/main/webapp/css/navbar.css
  src/main/webapp/css/user-page.css
  src/main/webapp/feed.html
  src/main/webapp/images/cinemaReviews1.svg
Labels: ready to merge

#53 Created FAQ Page + Modify icon on landing page
  src/main/java/com/google/codeu/data/Datastore.java
  src/main/java/com/google/codeu/servlets/BlobstoreUploadUrlServlet.java
  src/main/java/com/google/codeu/servlets/MarkerMessagesServlet.java
  src/main/webapp/aboutus.html
  src/main/webapp/community.html
  src/main/webapp/css/faq_page.css
  src/main/webapp/css/feed.css
  src/main/webapp/css/maps-page.css
  src/main/webapp/css/navbar.css
  src/main/webapp/css/user-page.css
  src/main/webapp/faq.html
  src/main/webapp/feed.html
  src/main/webapp/images/faqPage.jpg
  src/main/webapp/images/movieTicket.png
  src/main/webapp/index.html
  src/main/webapp/js/faq_page.js
  src/main/webapp/js/maps-page-loader.js
  src/main/webapp/js/messages-loader.js
  src/main/webapp/js/user-page-loader.js
  src/main/webapp/maps.html
  src/main/webapp/user-page.html
Labels: ready to merge

#56 Aggregate Sentiment Score
  src/main/java/com/google/codeu/data/Datastore.java
  src/main/java/com/google/codeu/servlets/AggregateSentimentScoreServlet.java
  src/main/java/com/google/codeu/servlets/LoginStatusServlet.java
  src/main/java/com/google/codeu/servlets/MessageByKeyServlet.java
  src/main/webapp/css/selectionMenu.css
  src/main/webapp/js/maps-page-loader.js
  src/main/webapp/maps.html
Labels: ready to merge

#59 Debug1
  src/main/webapp/aboutus.html
  src/main/webapp/css/selectionMenu.css
  src/main/webapp/index.html
  src/main/webapp/js/main.js
  src/main/webapp/js/messages-loader.js
  src/main/webapp/maps.html
Labels: ready to merge

#60 Redirect to login for users trying to run cinema-init but not login yet
  src/main/java/com/google/codeu/servlets/CinemaInitServlet.java
Labels: ready to merge

#61 Routing back message and speed up submission
  src/main/java/com/google/codeu/servlets/MarkerMessagesServlet.java
  src/main/webapp/js/maps-page-loader.js
  src/main/webapp/js/messages-loader.js
Labels: ready to merge
